openapi: 3.0.1
info:
  contact:
    email: otae@fundaciobit.org
    name: Departament de Govern Digital a la Fundació Bit
    url: http://otae.fundaciobit.org
  description: Conjunt de Serveis REST de PinbalAdmin per ser accedits des de l'exterior
  license:
    name: License Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: API REST EXTERNA de PinbalAdmin
  version: 1.0.0
externalDocs:
  description: Java Client (GovernIB Github)
  url: https://github.com/GovernIB/pinbaladmin/tree/pinbaladmin-1.0/pinbaladmin-api-externa-client
servers:
- url: /pinbaladminapi/externa
- url: http://localhost:8080/pinbaladminapi/externa
- url: https://dev.caib.es/pinbaladminapi/externa
- url: https://proves.caib.es/pinbaladminapi/externa
- url: https://se.caib.es/pinbaladminapi/externa
- url: https://www.caib.es/pinbaladminapi/externa
tags:
- description: Exemple de Servei JSON d'accés Públic
  name: Versio
- description: Exemple de Servei Securitzat
  name: ExempleSeguritzat
- description: TramitSistraService
  name: TramitSistraService
paths:
  /public/exemplepublic/versio:
    get:
      operationId: versio
      parameters:
      - description: Codi de l'idioma
        example: ca
        explode: true
        in: query
        name: idioma
        required: false
        schema:
          pattern: ^ca|es$
          type: string
        style: form
      responses:
        "404":
          content:
            application/json: {}
          description: Paràmetres incorrectes
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamplePojo'
          description: Versió i idioma
      summary: Versio de l'Aplicació
      tags:
      - Versio
      x-accepts: application/json
  /secure/exempleseguritzat/echo:
    get:
      operationId: echo
      parameters:
      - description: Cadena a retornar
        example: hola caracola
        explode: true
        in: query
        name: echoInput
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Respon el valor enviat per paràmetre
        "510":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConstantsWs'
          description: Només s'utilitza per crear fitxer de constants...
      security:
      - BasicAuth: []
      summary: Fa un ECHO
      tags:
      - ExempleSeguritzat
      x-accepts: application/json
  /secure/TramitSistraService/v1/resultado:
    get:
      operationId: getDatosFormularioFromTicket
      parameters:
      - description: Ticket del fomulario
        example: CFDEKWNL-UHMZR8T8-T8WTFOOR:MhufBxRLLomvdOjC9nZhPA==
        explode: true
        in: query
        name: ticket
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "401":
          content:
            application/json:
              schema:
                type: string
          description: No Autenticat
        "403":
          content:
            application/json:
              schema:
                type: string
          description: No Autoritzat
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
        "510":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Només s'utilitza per crear fitxer de constants...
      security:
      - BasicAuth: []
      summary: Retorna les dades del formulari
      tags:
      - TramitSistraService
      x-accepts: application/json
  /secure/TramitSistraService/v1/formulario:
    post:
      operationId: getUrlFormulari
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TramitSistraPojo'
        description: Dades de la petició
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "401":
          content:
            application/json:
              schema:
                type: string
          description: No Autenticat
        "403":
          content:
            application/json:
              schema:
                type: string
          description: No Autoritzat
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna la URL per iniciar el tramit
      tags:
      - TramitSistraService
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    ExamplePojo:
      example:
        versio: versio
      properties:
        versio:
          type: string
      type: object
    ConstantsWs:
      properties:
        ROLE_EJB_FULL_ACCESS:
          default: PAD_ADMIN
          description: Constant ROLE_EJB_FULL_ACCESS
          readOnly: true
          type: string
        ROLE_EJB_BASIC_ACCESS:
          description: Constant ROLE_EJB_BASIC_ACCESS
          format: int32
          readOnly: true
          type: integer
        ROLE_EJB_WS_ACCESS:
          description: Constant ROLE_EJB_WS_ACCESS
          format: int32
          readOnly: true
          type: integer
      required:
      - ROLE_EJB_BASIC_ACCESS
      - ROLE_EJB_FULL_ACCESS
      - ROLE_EJB_WS_ACCESS
      type: object
    Resultado:
      example:
        pdf: pdf
        cancelado: true
        xml: xml
        idSesionFormulario: idSesionFormulario
      properties:
        idSesionFormulario:
          type: string
        cancelado:
          type: boolean
        xml:
          type: string
        pdf:
          type: string
      type: object
    RestExceptionInfo:
      description: Estructura de dades utilitzada per passar informació d'un error
      properties:
        code:
          description: Codi de HTTP de l'error. Veure https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.
          format: int32
          type: integer
        errorMessage:
          description: Missatge de l'error
          type: string
        stackTrace:
          description: Stacktrace de l'excepció si n'hi hagués.
          type: string
        causeException:
          description: Tipus de l'excepció origen (cause) si n'hi hagués.
          type: string
        causeStackTrace:
          description: Stacktrace de l'excepció origen (cause) si n'hi hagués.
          type: string
      required:
      - code
      - errorMessage
      type: object
    ParametrosApertura:
      description: Lista parámetros (opcional)
      example:
        codigo: codigo1
        valor: valor1
      properties:
        codigo:
          description: codigo
          example: codigo1
          type: string
        valor:
          description: valor
          example: valor1
          type: string
      type: object
    TramitSistraPojo:
      example:
        entidad: A04003003
        xmlDatosActuales: < XML B64>
        parametrosApertura:
        - codigo: codigo1
          valor: valor1
        - codigo: codigo1
          valor: valor1
        idSesionFormulario: CFDEKWNL-UHMZR8T8-T8WTFOOR
        idioma: es
        usuario:
          apellido2: Apellido 2
          apellido1: Apellido 1
          nif: 11111111H
          nombre: Nombre
        urlCallback: <URL CALLBACK SISTRA2>
        idFormularioExterno: FOR-EXT-1
      properties:
        entidad:
          description: DIR3 de la entidad
          example: A04003003
          type: string
        idSesionFormulario:
          description: Id sesión formulario de SISTRA2
          example: CFDEKWNL-UHMZR8T8-T8WTFOOR
          type: string
        idFormularioExterno:
          description: Id formulario externo a ejecutar
          example: FOR-EXT-1
          type: string
        idioma:
          description: "Idioma (es, ca, en)"
          example: es
          type: string
        usuario:
          $ref: '#/components/schemas/Usuario'
        xmlDatosActuales:
          description: XML con los datos actuales del formulario en Base64
          example: < XML B64>
          type: string
        parametrosApertura:
          description: Lista parámetros (opcional)
          items:
            $ref: '#/components/schemas/ParametrosApertura'
          type: array
        urlCallback:
          description: Url callback SISTRA2
          example: <URL CALLBACK SISTRA2>
          type: string
      type: object
    Usuario:
      description: Usuario autenticado
      example:
        apellido2: Apellido 2
        apellido1: Apellido 1
        nif: 11111111H
        nombre: Nombre
      properties:
        nif:
          description: nif
          example: 11111111H
          type: string
        nombre:
          description: Nombre
          example: Nombre
          type: string
        apellido1:
          description: Primer apellido
          example: Apellido 1
          type: string
        apellido2:
          description: Segundo apellido
          example: Apellido 2
          type: string
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http

